# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

%global goipath goji.io
%global gourl https://github.com/goji/goji
Version: 2.0.2

%gometa

%global common_description %{expand:
Goji is a minimalistic and flexible HTTP request multiplexer for Go (golang).}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Goji is a minimalistic and flexible HTTP request multiplexer for Go (golang)

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Jan 23 2022 Markus Falb <jeremy@mafalb.at> - 2.0.2-1
- Initial package
